In [94]:
import numpy as np

In [95]:
ls=[[[1,2,3]]]
arr=np.array(ls)
type(arr)

numpy.ndarray

In [96]:
arr.ndim

3

In [97]:
arr.size

3

In [98]:
arr.shape

(1, 1, 3)

In [99]:
np.array([12,43,23,2.5,2+5j])

array([12. +0.j, 43. +0.j, 23. +0.j,  2.5+0.j,  2. +5.j])

In [100]:
np.array([12,43,23,2.5],dtype='int')

array([12, 43, 23,  2])

In [101]:
np.array([12,43,23,2.5,2+5j],dtype='str')

array(['12', '43', '23', '2.5', '(2+5j)'], dtype='<U6')

In [102]:
new_arr=np.array([[12,43,23],
         [1,2,3],
         [5,6,7]])

new_arr.ndim

2

In [103]:
new_arr=np.array([[12,43,23],
         [1,2,3],
         [5,6,np.nan]])
print(new_arr)

[[12. 43. 23.]
 [ 1.  2.  3.]
 [ 5.  6. nan]]


In [104]:
new_arr=np.array([[12,43,23],
         [1,2,3],
         [5,6,None]])

print(new_arr)
new_arr.dtype

[[12 43 23]
 [1 2 3]
 [5 6 None]]


dtype('O')

In [105]:
np.arange(1,11.5)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [106]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [109]:
new_arr=np.array([[12,43,23],
         [1,2,3],
         [5,6,7]])

new_arr.flatten()

array([12, 43, 23,  1,  2,  3,  5,  6,  7])

In [110]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [111]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [112]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [113]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [114]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [115]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [116]:
np.identity(5)  #to genrate identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [117]:
np.random.randint(1,60,8)

array([29, 46,  7, 51, 45, 42, 21, 16], dtype=int32)

In [118]:
np.random.randint(100,200,[3,4])

array([[109, 128, 153, 154],
       [167, 170, 192, 187],
       [127, 177, 159, 150]], dtype=int32)

In [119]:
np.random.rand(1,10,
    5)

array([[[0.12643674, 0.6216955 , 0.91281674, 0.41135091, 0.64355961],
        [0.79604095, 0.33894408, 0.41362665, 0.31359763, 0.18323896],
        [0.70942026, 0.06608111, 0.22214507, 0.02076208, 0.68469002],
        [0.79495918, 0.7332011 , 0.30599506, 0.58929312, 0.50954487],
        [0.89108114, 0.51469239, 0.23911291, 0.6851346 , 0.50603227],
        [0.43336537, 0.09393048, 0.72903063, 0.07800359, 0.09930761],
        [0.39519727, 0.49004619, 0.37647665, 0.14388218, 0.53144337],
        [0.92193022, 0.35497424, 0.8853394 , 0.60073974, 0.47387598],
        [0.67063147, 0.39380336, 0.75117269, 0.10586149, 0.75126927],
        [0.02379851, 0.17883931, 0.99216785, 0.01507958, 0.26584187]]])

In [120]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [123]:
arr=np.arange(1,11).reshape([2,5])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [124]:
new_arr=arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [125]:
arr[0][0]=100
arr


array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [126]:
new_arr_copy=arr.copy()
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [128]:
arr.transpose()

array([[100,   6],
       [  2,   7],
       [  3,   8],
       [  4,   9],
       [  5,  10]])